apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: shopnow
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://sankarrajsundaram_db_user:zUQJmY529YRUS21u@sankardbcluster.othbgsa.mongodb.net/"
